import type { Metadata } from "next";
import localFont from "next/font/local";
import "@styles/globals.scss";
import { ThemeProvider } from "@contexts/theme-context";
import { AppContextProvider } from "@contexts/app-context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const philosopher = localFont({
  src: "./fonts/Philosopher-Regular.ttf",
  variable: "--font-philosopher-regular",
  weight: "100 900",
});

const philosopherBold = localFont({
  src: "./fonts/Philosopher-Bold.ttf",
  variable: "--font-philosopher-bold",
  weight: "700",
});

const philosopherItalic = localFont({
  src: "./fonts/Philosopher-Italic.ttf",
  variable: "--font-philosopher-italic",
  weight: "400",
});

const philosopherBoldItalic = localFont({
  src: "./fonts/Philosopher-BoldItalic.ttf",
  variable: "--font-philosopher-bold-italic",
  weight: "700",
});

const mulish = localFont({
  src: "./fonts/Mulish-VariableFont_wght.ttf",
  variable: "--font-mulish",
  weight: "100 900",
});

const mulishItalic = localFont({
  src: "./fonts/Mulish-Italic-VariableFont_wght.ttf",
  variable: "--font-mulish-italic",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-brilliant ${philosopher.variable} ${philosopherBold.variable} ${philosopherItalic.variable} ${philosopherBoldItalic.variable} ${mulish.variable} ${mulishItalic.variable}`}
      >
        <ThemeProvider
          attribute={"class"}
          defaultTheme={"dark"}
          enableSystem={false}
        >
          <AppContextProvider>{children}</AppContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
