export const DATA_FODLER = "./data";

export interface Name {
  firstName: string;
  lastName: string;
}

// Array of 100 fake names
export const fakeNames: Name[] = [
  { firstName: "Aiden", lastName: "Parker" },
  { firstName: "Sophia", lastName: "Martinez" },
  { firstName: "Liam", lastName: "O'Connor" },
  { firstName: "Emma", lastName: "Chen" },
  { firstName: "Noah", lastName: "Patel" },
  { firstName: "Olivia", lastName: "Rossi" },
  { firstName: "Ethan", lastName: "Nguyen" },
  { firstName: "Ava", lastName: "Thompson" },
  { firstName: "Mason", lastName: "Kim" },
  { firstName: "Isabella", lastName: "Garcia" },
  { firstName: "Logan", lastName: "Smith" },
  { firstName: "Mia", lastName: "Brown" },
  { firstName: "Lucas", lastName: "Hernandez" },
  { firstName: "Amelia", lastName: "Davis" },
  { firstName: "Jackson", lastName: "Lee" },
  { firstName: "Charlotte", lastName: "Wilson" },
  { firstName: "Oliver", lastName: "Martinez" },
  { firstName: "Harper", lastName: "Clark" },
  { firstName: "Elijah", lastName: "Lewis" },
  { firstName: "Evelyn", lastName: "Walker" },
  { firstName: "James", lastName: "Young" },
  { firstName: "Abigail", lastName: "Hall" },
  { firstName: "Benjamin", lastName: "Allen" },
  { firstName: "Emily", lastName: "King" },
  { firstName: "Alexander", lastName: "Wright" },
  { firstName: "Ella", lastName: "Scott" },
  { firstName: "Henry", lastName: "Green" },
  { firstName: "Grace", lastName: "Adams" },
  { firstName: "Sebastian", lastName: "Baker" },
  { firstName: "Chloe", lastName: "Gonzalez" },
  { firstName: "Daniel", lastName: "Nelson" },
  { firstName: "Lily", lastName: "Carter" },
  { firstName: "Matthew", lastName: "Mitchell" },
  { firstName: "Sofia", lastName: "Perez" },
  { firstName: "Samuel", lastName: "Roberts" },
  { firstName: "Avery", lastName: "Turner" },
  { firstName: "David", lastName: "Phillips" },
  { firstName: "Scarlett", lastName: "Campbell" },
  { firstName: "Joseph", lastName: "Parker" },
  { firstName: "Victoria", lastName: "Evans" },
  { firstName: "Carter", lastName: "Edwards" },
  { firstName: "Madison", lastName: "Collins" },
  { firstName: "Owen", lastName: "Stewart" },
  { firstName: "Aria", lastName: "Sanchez" },
  { firstName: "Wyatt", lastName: "Morris" },
  { firstName: "Penelope", lastName: "Rogers" },
  { firstName: "John", lastName: "Reed" },
  { firstName: "Layla", lastName: "Cook" },
  { firstName: "Jack", lastName: "Morgan" },
  { firstName: "Zoe", lastName: "Bell" },
  { firstName: "Luke", lastName: "Murphy" },
  { firstName: "Nora", lastName: "Bailey" },
  { firstName: "Jayden", lastName: "Rivera" },
  { firstName: "Lillian", lastName: "Cooper" },
  { firstName: "Dylan", lastName: "Richardson" },
  { firstName: "Hannah", lastName: "Cox" },
  { firstName: "Isaac", lastName: "Howard" },
  { firstName: "Addison", lastName: "Ward" },
  { firstName: "Gabriel", lastName: "Torres" },
  { firstName: "Aubrey", lastName: "Peterson" },
  { firstName: "Anthony", lastName: "Gray" },
  { firstName: "Ellie", lastName: "Ramirez" },
  { firstName: "Christopher", lastName: "James" },
  { firstName: "Stella", lastName: "Watson" },
  { firstName: "Andrew", lastName: "Brooks" },
  { firstName: "Natalie", lastName: "Kelly" },
  { firstName: "Thomas", lastName: "Sanders" },
  { firstName: "Hazel", lastName: "Price" },
  { firstName: "Joshua", lastName: "Bennett" },
  { firstName: "Violet", lastName: "Wood" },
  { firstName: "Charles", lastName: "Barnes" },
  { firstName: "Aurora", lastName: "Ross" },
  { firstName: "Caleb", lastName: "Henderson" },
  { firstName: "Savannah", lastName: "Coleman" },
  { firstName: "Ryan", lastName: "Jenkins" },
  { firstName: "Brooklyn", lastName: "Perry" },
  { firstName: "Nathan", lastName: "Powell" },
  { firstName: "Bella", lastName: "Long" },
  { firstName: "Aaron", lastName: "Patterson" },
  { firstName: "Claire", lastName: "Hughes" },
  { firstName: "Christian", lastName: "Flores" },
  { firstName: "Skylar", lastName: "Washington" },
  { firstName: "Jonathan", lastName: "Butler" },
  { firstName: "Lucy", lastName: "Simmons" },
  { firstName: "Thomas", lastName: "Foster" },
  { firstName: "Paisley", lastName: "Bryant" },
  { firstName: "Hunter", lastName: "Alexander" },
  { firstName: "Kennedy", lastName: "Russell" },
  { firstName: "Connor", lastName: "Griffin" },
  { firstName: "Caroline", lastName: "Diaz" },
  { firstName: "Jose", lastName: "Hayes" },
  { firstName: "Anna", lastName: "Myers" },
  { firstName: "Brayden", lastName: "Ford" },
  { firstName: "Allison", lastName: "Hamilton" },
  { firstName: "Angel", lastName: "Carter" },
  { firstName: "Gabriella", lastName: "Graham" },
  { firstName: "Isaiah", lastName: "Sullivan" },
  { firstName: "Sadie", lastName: "Wallace" },
  { firstName: "Charles", lastName: "West" },
  { firstName: "Mila", lastName: "Cole" },
];

// fakeBooks.ts

// Array of 100 fake book titles
export const bookTitles: string[] = [
  "Whispers of the Forgotten",
  "The Quantum Garden",
  "Shadow over Elm Street",
  "Luminescent Nights",
  "Echoes of Tomorrow",
  "The Alchemist's Compass",
  "Broken Wings",
  "Celestial Boundaries",
  "The Silent Symphony",
  "Mirrors of the Mind",
  "Veil of Shadows",
  "The Last Ember",
  "Threads of Fate",
  "Crimson Horizons",
  "The Hidden Library",
  "Stardust Dreams",
  "The Forgotten Isle",
  "Infinite Echoes",
  "The Golden Compass",
  "Whispers in the Wind",
  "The Sapphire Sea",
  "Twilight Sonata",
  "The Iron Fortress",
  "Veins of the Earth",
  "The Silver Lining",
  "Embers of Time",
  "The Obsidian Gate",
  "Radiant Shadows",
  "The Emerald Path",
  "Whirlwind Hearts",
  "The Crystal Labyrinth",
  "Beneath the Willow",
  "The Forgotten Manuscript",
  "Silent Waters",
  "The Celestial Forge",
  "Dawn of the Phoenix",
  "Whispers of the Ancients",
  "The Midnight Oracle",
  "Echoes of Silence",
  "The Golden Horizon",
  "Veil of Illusions",
  "The Last Horizon",
  "Starlit Journey",
  "The Hidden Fortress",
  "Radiant Dawn",
  "The Alabaster Tower",
  "Whispers of the Forest",
  "The Infinite Maze",
  "Embers of the Heart",
  "The Sapphire Mirror",
  "Celestial Voyage",
  "The Forgotten Realm",
  "Twilight Dreams",
  "The Iron Will",
  "Veins of Gold",
  "The Silver Horizon",
  "Echoes of the Deep",
  "The Obsidian Heart",
  "Radiant Echoes",
  "The Emerald Compass",
  "Whirlwind Adventures",
  "The Crystal Veil",
  "Beneath the Stars",
  "The Forgotten Voyage",
  "Silent Horizons",
  "The Celestial Symphony",
  "Dawn of the Dragon",
  "Whispers of the Moon",
  "The Midnight Journey",
  "Echoes of Eternity",
  "The Golden Voyage",
  "Veil of Stars",
  "The Last Ember",
  "Starlit Paths",
  "The Hidden Citadel",
  "Radiant Twilight",
  "The Alabaster Shore",
  "Whispers of Time",
  "The Infinite Quest",
  "Embers of Destiny",
  "The Sapphire Voyage",
  "Celestial Reflections",
  "The Forgotten Guardians",
  "Twilight Legends",
  "The Iron Heart",
  "Veins of Power",
  "The Silver Locket",
  "Echoes of the Ancients",
  "The Obsidian Path",
  "Radiant Shadows",
  "The Emerald Quest",
  "Whirlwind Hearts",
  "The Crystal Nexus",
  "Beneath the Aurora",
  "The Forgotten Odyssey",
  "Silent Reflections",
  "The Celestial Bridge",
  "Dawn of Shadows",
  "Whispers of the Stars",
  "The Midnight Garden",
  "Echoes of the Heart",
  "The Golden Labyrinth",
  "Veil of Time",
  "The Last Horizon",
  "Starlit Echoes",
  "The Hidden Sanctuary",
  "Radiant Journeys",
  "The Alabaster Sky",
  "Whispers of the Wild",
  "The Infinite Horizon",
  "Embers of Courage",
  "The Sapphire Dream",
  "Celestial Horizons",
  "The Forgotten Kingdom",
  "Twilight Reflections",
  "The Iron Fortress",
  "Veins of Destiny",
  "The Silver Star",
  "Echoes of the Void",
];

// Array of 100 fake book subtitles
export const bookSubtitles: string[] = [
  "Echoes from a Lost Era",
  "Exploring the Microcosm",
  "A Tale of Hidden Dangers",
  "Stories Under the Stars",
  "Visions of the Future",
  "Journey to Self-Discovery",
  "A Story of Resilience",
  "Navigating the Cosmos",
  "Music Beyond Words",
  "Reflections on Consciousness",
  "Mysteries Unveiled",
  "Fighting for the Future",
  "Interwoven Destinies",
  "Adventures in the Unknown",
  "Secrets of the Ancients",
  "Chasing Celestial Wonders",
  "Legends of the Lost Land",
  "Time's Endless Cycle",
  "Navigating Life's Journey",
  "Messages from Afar",
  "Voyage to the Unknown",
  "Melodies of Dusk",
  "Battles for Freedom",
  "Stories Beneath the Surface",
  "Finding Hope in Darkness",
  "Chronicles of the Past",
  "Passage to Another Realm",
  "Light in the Dark",
  "Journey Through Nature",
  "Love in Turbulent Times",
  "Puzzles of the Mind",
  "Tales of Serenity",
  "Unveiling Lost Knowledge",
  "Calm Amidst Chaos",
  "Creating the Stars",
  "Rise from the Ashes",
  "Legends Reborn",
  "Predictions and Prophecies",
  "Finding Peace Within",
  "Explorations Beyond",
  "Seeing Beyond the Surface",
  "Endings and Beginnings",
  "Navigating the Night Sky",
  "Secrets of Strength",
  "New Beginnings",
  "Guardians of the Realm",
  "Nature's Secrets",
  "Challenges of the Mind",
  "Passions Unleashed",
  "Reflections of Truth",
  "Journey to the Stars",
  "Adventures in Mystery",
  "Visions of the Night",
  "Stories of Determination",
  "Prospecting for Success",
  "Exploring New Frontiers",
  "Mysteries of the Ocean",
  "Tales of Strength",
  "Light Through Time",
  "Guiding Through Life",
  "Thrills and Excitement",
  "Secrets Revealed",
  "Stories of the Night",
  "Exploring the Unknown",
  "Peace in Exploration",
  "Harmony in the Heavens",
  "Legends of Fire",
  "Lunar Secrets",
  "Travels in the Dark",
  "Timeless Tales",
  "Adventures on the High Seas",
  "Navigating the Galaxy",
  "Preserving the Flame",
  "Guided by Light",
  "Fortress of Secrets",
  "Beauty in Transition",
  "Journeys by the Sea",
  "Chronicles of Change",
  "Pursuit of Knowledge",
  "Shaping the Future",
  "Sailing the Blue",
  "Thoughts Among the Stars",
  "Protectors of the Past",
  "Myths of the Dusk",
  "Stories of Courage",
  "Harnessing Strength",
  "Treasures of the Heart",
  "Legacies Left Behind",
  "Journey Through Darkness",
  "Balancing Light and Dark",
  "Search for the Green Gem",
  "Love in Motion",
  "Connecting Worlds",
  "Northern Lights Adventures",
  "Epic Tales Revisited",
  "Meditations on Life",
  "Connecting Realms",
  "Emerging from Darkness",
  "Messages from the Universe",
  "Flowers in the Dark",
  "Emotional Journeys",
  "Navigating Complexity",
  "Chronicles Across Ages",
  "Explorations Beyond Limits",
  "Resonance of the Night",
  "Safe Havens in Chaos",
  "Paths to Enlightenment",
  "Clouds of Imagination",
  "Nature's Voice",
  "Boundless Adventures",
  "Acts of Bravery",
  "Visions in Blue",
  "Exploring the Infinite",
  "Rise and Fall",
  "Contemplations at Dusk",
  "Strongholds of Strength",
  "Bloodlines and Fate",
  "Guiding Light",
  "Silence in Space",
];

// Helper function to assign random genres
export function getRandomGenre(): string {
  const genres = [
    "Fantasy",
    "Science Fiction",
    "Mystery",
    "Romance",
    "Thriller",
    "Horror",
    "Non-Fiction",
    "Historical",
    "Young Adult",
    "Adventure",
    "Biography",
    "Self-Help",
    "Graphic Novel",
    "Poetry",
    "Drama",
  ];
  return genres[Math.floor(Math.random() * genres.length)];
}
